#!/bin/bash

while true; do
      read -p "Where do you want to go? " input
      case $input in
      	   d2017  ) cd /home/$USER/Dropbox/Skole/; break;;
	   l2017 ) cd /HDD1/school; break;;
	   undass ) cd /home/$USER/Dropbox/Skole/Undass; break;;
	   [qnQN]*     ) break;;
	   * ) echo "Please answer yes or no.";;
      esac
done
